; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
upload_speed = 115200
framework = arduino
monitor_speed = 115200
upload_flags = 
	--no-stub
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	madhephaestus/ESP32Servo
	adafruit/Adafruit NeoPixel
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	mikalhart/TinyGPSPlus@^1.0.3
	hideakitai/MPU9250@^0.4.8
	tomstewart89/BasicLinearAlgebra@^5.1
